spring:
  application:
    name: demo

  server:
    port: 8080
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create  # 하이버네이트의 DDL 자동 실행 옵션 설정

  h2:
    console:
      enabled: true  # H2 콘솔 웹 인터페이스 활성화 
      path: /h2-console  # H2 콘솔에 접근할 수 있는 경로 설정

# 디버깅을 위한 로깅 설정
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          description:
            sql:
              BasicBinder: TRACE

# Nyan-Cat
config:
  title: MY APPLICATION
  author: MOSEOH
